name: unittest
on: [push, pull_request]

jobs:
  unittest:
    name: unittest
    strategy:
      matrix:
        go-version: ['oldstable', 'stable']
    runs-on: ubuntu-latest
    steps:
      - name: Go ${{ matrix.go-version }} setup
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }} 

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unittest ${{ matrix.go-version }}
        run: make unittest 
